# Generated by Django 6.0.6 on 2026-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
