# Generated by Django 6.0.6 on 2026-09-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_booking_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('waiting_photographer', 'Waiting for Photographer'), ('photographer_accepted', 'Photographer Accepted'), ('photographer_rejected', 'Photographer Rejected'), ('waiting_admin', 'Waiting for Admin'), ('confirmed', 'Confirmed'), ('work_started', 'Work Started'), ('in_progress', 'Work In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='payment_pending', max_length=30),
        ),
    ]
