# Generated by Django 6.0.6 on 2026-10-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_reschedulerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RescheduleRequest',
        ),
    ]
