# Generated by Django 6.0.6 on 2026-09-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
