# Generated by Django 6.0.6 on 2026-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_reschedulerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_by',
            field=models.CharField(choices=[('user', 'User'), ('photographer', 'Photographer')], default='user', max_length=20),
        ),
    ]
