# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='plan_mode',
            field=models.CharField(
                blank=True,
                choices=[('', 'Not selected'), ('free', 'Free'), ('gold', 'Gold'), ('platinum', 'Platinum')],
                default='',
                max_length=20,
            ),
        ),
    ]
