# Generated by Django 6.0.6 on 2026-07-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_portfoliofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliolink',
            name='profile',
        ),
        migrations.DeleteModel(
            name='PortfolioFile',
        ),
        migrations.DeleteModel(
            name='PortfolioLink',
        ),
    ]
