# Generated by Django 6.0.6 on 2026-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0005_remove_portfoliolink_profile_delete_portfoliofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='portfolio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='photographer_portfolios/'),
        ),
    ]
