# Generated by Django 6.0.6 on 2026-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0006_photographerprofile_portfolio_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='verification_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
