# Generated by Django 6.0.6 on 2026-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0007_photographerprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
