# Generated by Django 6.0.6 on 2026-07-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0009_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
