# Generated by Django 6.0.6 on 2026-07-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0011_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
