# Generated by Django 6.0.6 on 2026-07-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0012_delete_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20)),
                ('afternoon_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='photographer.photographerprofile')),
            ],
            options={
                'unique_together': {('photographer', 'date')},
            },
        ),
    ]
