# Generated by Django 6.0.6 on 2026-07-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0013_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
