# Generated by Django 6.0.6 on 2026-07-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0016_availabilityexception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyavailability',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
