# Generated by Django 6.0.6 on 2026-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0017_alter_weeklyavailability_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyavailability',
            name='afternoon',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='morning',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20),
        ),
    ]
