# Generated by Django 6.0.6 on 2026-09-03 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0018_alter_weeklyavailability_afternoon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='photographer.photographerprofile')),
            ],
            options={
                'unique_together': {('photographer', 'hours')},
            },
        ),
    ]
