# Generated by Django 5.1.6 on 2026-10-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0021_photographerpasswordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_mode', models.CharField(choices=[('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_payments', to='photographer.photographerprofile')),
            ],
        ),
    ]
