# Generated by Django 5.1.6 on 2026-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0022_verificationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationpayment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
