# Generated by Django 5.1.6 on 2026-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshire_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('verification_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
